impoved the if statement using grep

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -6,6 +6,7 @@
 #    automatically configure a Ubuntu machine to respect above requirements
 # 	- write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task
 
+
 new_str_err="server_name _;\n\terror_page 404 \/404.html;"
 
 new_str_loc="server_name _;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t\t}"
@@ -16,14 +17,21 @@ sudo chmod 777 /var/www/html/404.html
 echo "Ceci n'est pas une page" > /var/www/html/404.html
 sudo chmod 644 /var/www/html/404.html
 
+# check if the config's file already exist otherwise I exit.
+if [ ! -f "/etc/nginx/sites-available/default" ]; then
+    echo "Nginx configuration file not found. Please adjust the path."
+    exit 1
+fi
+
 # check if the string "location = 404.html" in the file before add it
-if ! sudo grep -q "location = \/404.html "; then
+if ! grep -q "location = \/404.html " /etc/nginx/sites-available/default; then
 	sudo sed -i 's/server_name _;/'"$new_str_loc"'/' /etc/nginx/sites-available/default
 fi
 
 # check if the string "error_error" in the file before add it
-if ! sudo grep -q  "error_page 404 \/404.html;"; then
+if ! sudo grep -q  "error_page 404 \/404.html;" /etc/nginx/sites-available/default; then
 	sudo sed -i 's/server_name _;/'"$new_str_err"'/' /etc/nginx/sites-available/default
 fi
 
+# restart the nginx.
 sudo service nginx restart
